import type { Release, Slice } from './types';

/**
 * Synthetic seed. "Harbourline Insurance" and all metadata, names, record counts
 * and test results are invented for this demo. No Salesforce org is involved.
 */
export const TARGET_COMPONENTS = [
  'CustomObject:Case',
  'CustomField:Case.Status',
  'CustomField:Case.Priority',
  'CustomField:Case.Region__c',
  'CustomField:Case.Legacy_Region__c',
  'ApexClass:CaseRouter',
  'ApexClass:CaseRouterTest',
  'Flow:Case_Assignment',
  'PermissionSet:Support_Agent',
];

const agentforceV1: Slice = {
  id: 'agentforce-triage-v1',
  name: 'Agentforce case-triage agent',
  revision: 1,
  atomic: true,
  description:
    'An AI-assisted change set that adds a case-triage agent. Its happy-path conversation demo passes in the developer sandbox.',
  provenance: 'Synthetic seed: fictional AI-assisted change set, written by hand for this demo.',
  changes: [
    {
      id: 'a1',
      type: 'GenAiPlannerBundle',
      apiName: 'Case_Triage_Agent',
      action: 'add',
      origin: 'ai-assisted',
      author: 'Agent draft, reviewed by R. Osei',
      summary: 'New agent that triages inbound cases and escalates urgent ones.',
      dependsOn: ['GenAiPlugin:Case_Triage_Topic'],
      diff: {
        before: [],
        after: [
          '<GenAiPlannerBundle>',
          '  <masterLabel>Case Triage Agent</masterLabel>',
          '  <plannerType>AiCopilot__ReAct</plannerType>',
          '  <genAiPlugins>Case_Triage_Topic</genAiPlugins>',
          '</GenAiPlannerBundle>',
        ],
      },
    },
    {
      id: 'a2',
      type: 'GenAiPlugin',
      apiName: 'Case_Triage_Topic',
      action: 'add',
      origin: 'ai-assisted',
      author: 'Agent draft, reviewed by R. Osei',
      summary: 'Topic: classify a case, summarise it and escalate if urgent.',
      dependsOn: ['GenAiFunction:Escalate_Case', 'GenAiFunction:Summarise_Case'],
      diff: {
        before: [],
        after: [
          '<GenAiPlugin>',
          '  <masterLabel>Case triage</masterLabel>',
          '  <genAiFunctions>Escalate_Case</genAiFunctions>',
          '  <genAiFunctions>Summarise_Case</genAiFunctions>',
          '  <scope>Only act on cases the running user can edit.</scope>',
          '</GenAiPlugin>',
        ],
      },
    },
    {
      id: 'a3',
      type: 'GenAiFunction',
      apiName: 'Escalate_Case',
      action: 'add',
      origin: 'ai-assisted',
      author: 'Agent draft, reviewed by R. Osei',
      summary: 'Action that calls Apex to raise priority and reassign the case.',
      dependsOn: ['ApexClass:CaseEscalationService'],
      diff: {
        before: [],
        after: [
          '<GenAiFunction>',
          '  <masterLabel>Escalate case</masterLabel>',
          '  <invocationTarget>CaseEscalationService</invocationTarget>',
          '  <invocationTargetType>apex</invocationTargetType>',
          '</GenAiFunction>',
        ],
      },
    },
    {
      id: 'a4',
      type: 'GenAiFunction',
      apiName: 'Summarise_Case',
      action: 'add',
      origin: 'ai-assisted',
      author: 'Agent draft, reviewed by R. Osei',
      summary: 'Action that runs the Case_Summary prompt template.',
      dependsOn: ['GenAiPromptTemplate:Case_Summary'],
      diff: {
        before: [],
        after: [
          '<GenAiFunction>',
          '  <masterLabel>Summarise case</masterLabel>',
          '  <invocationTarget>Case_Summary</invocationTarget>',
          '  <invocationTargetType>generatePromptResponse</invocationTargetType>',
          '</GenAiFunction>',
        ],
      },
    },
    {
      id: 'a5',
      type: 'GenAiPromptTemplate',
      apiName: 'Case_Summary',
      action: 'add',
      origin: 'ai-assisted',
      author: 'Agent draft, reviewed by R. Osei',
      summary: 'Prompt template that summarises a case, using the customer tier.',
      dependsOn: ['CustomObject:Case', 'CustomField:Case.Customer_Tier__c'],
      diff: {
        before: [],
        after: [
          '<GenAiPromptTemplate>',
          '  <masterLabel>Case summary</masterLabel>',
          '  <content>Summarise {!$Input:Case.Subject} for a',
          '    {!$Input:Case.Customer_Tier__c} customer in 3 lines.</content>',
          '</GenAiPromptTemplate>',
        ],
      },
    },
    {
      id: 'a6',
      type: 'PermissionSet',
      apiName: 'Agent_Case_Access',
      action: 'add',
      origin: 'ai-assisted',
      author: 'Agent draft, reviewed by R. Osei',
      summary: 'Access for the agent user so the actions can run.',
      dependsOn: ['CustomObject:Case'],
      diff: {
        before: [],
        after: [
          '<PermissionSet>',
          '  <objectPermissions>',
          '    <object>Case</object>',
          '    <allowRead>true</allowRead><allowEdit>true</allowEdit>',
          '    <modifyAllRecords>true</modifyAllRecords>',
          '  </objectPermissions>',
          '  <fieldPermissions><field>Case.Status</field><editable>true</editable></fieldPermissions>',
          '</PermissionSet>',
        ],
      },
    },
  ],
  permissions: [
    {
      id: 'p1',
      permissionSet: 'Agent_Case_Access',
      kind: 'object',
      target: 'Case',
      before: 'none',
      after: 'modifyAll',
      assignedTo: 'the agent user (acts for every chat session)',
    },
    {
      id: 'p2',
      permissionSet: 'Agent_Case_Access',
      kind: 'field',
      target: 'Case.Status',
      before: 'none',
      after: 'edit',
      assignedTo: 'the agent user (acts for every chat session)',
    },
  ],
  tests: [
    {
      id: 't1',
      name: 'Conversation: customer asks for a case update',
      kind: 'agent-conversation',
      covers: ['GenAiPlannerBundle:Case_Triage_Agent', 'GenAiPlugin:Case_Triage_Topic', 'GenAiFunction:Summarise_Case'],
      scenario: 'happy-path',
      result: 'pass',
      source: 'Synthetic test record (developer sandbox demo run)',
    },
  ],
};

/** Pre-written synthetic revision. Shown as a fixture, not generated. */
export const agentforceV2: Slice = {
  ...agentforceV1,
  id: 'agentforce-triage-v2',
  revision: 2,
  parentId: agentforceV1.id,
  description:
    'Revision 2 adds the missing Apex service and field, narrows the agent permission set, and adds negative and permission tests.',
  provenance:
    'Synthetic seed: a remediation revision written in advance for this demo. Nothing is generated by the app.',
  changes: [
    ...agentforceV1.changes.filter((c) => c.id !== 'a6'),
    {
      ...agentforceV1.changes.find((c) => c.id === 'a6')!,
      summary: 'Access for the agent user, narrowed to Read on Case and Edit on Case.Status.',
      diff: {
        before: [],
        after: [
          '<PermissionSet>',
          '  <objectPermissions>',
          '    <object>Case</object>',
          '    <allowRead>true</allowRead><allowEdit>false</allowEdit>',
          '    <modifyAllRecords>false</modifyAllRecords>',
          '  </objectPermissions>',
          '  <fieldPermissions><field>Case.Status</field><editable>true</editable></fieldPermissions>',
          '</PermissionSet>',
        ],
      },
    },
    {
      id: 'a7',
      type: 'ApexClass',
      apiName: 'CaseEscalationService',
      action: 'add',
      origin: 'ai-assisted',
      author: 'Agent draft, reviewed by R. Osei',
      summary: 'Invocable Apex that raises priority and reassigns, with sharing enforced.',
      dependsOn: ['CustomObject:Case', 'CustomField:Case.Priority'],
      diff: {
        before: [],
        after: [
          'public with sharing class CaseEscalationService {',
          '  @InvocableMethod(label=\'Escalate case\')',
          '  public static void escalate(List<Id> caseIds) {',
          '    List<Case> cases = [SELECT Id, Priority FROM Case',
          '                        WHERE Id IN :caseIds WITH USER_MODE];',
          '    for (Case c : cases) c.Priority = \'High\';',
          '    update as user cases;',
          '  }',
          '}',
        ],
      },
    },
    {
      id: 'a8',
      type: 'ApexClass',
      apiName: 'CaseEscalationServiceTest',
      action: 'add',
      origin: 'ai-assisted',
      author: 'Agent draft, reviewed by R. Osei',
      summary: 'Apex tests for escalation, including a user without edit access.',
      dependsOn: ['ApexClass:CaseEscalationService'],
      isTest: true,
      diff: {
        before: [],
        after: [
          '@IsTest private class CaseEscalationServiceTest {',
          '  @IsTest static void raisesPriority() { /* ... */ }',
          '  @IsTest static void readOnlyUserCannotEscalate() { /* ... */ }',
          '}',
        ],
      },
    },
    {
      id: 'a9',
      type: 'CustomField',
      apiName: 'Case.Customer_Tier__c',
      action: 'add',
      origin: 'human',
      author: 'M. Laine',
      summary: 'Picklist used by the case summary prompt.',
      dependsOn: ['CustomObject:Case'],
      field: { after: { dataType: 'Picklist', values: ['Gold', 'Silver', 'Bronze'] }, populatedRecords: 0 },
      diff: {
        before: [],
        after: ['<CustomField>', '  <fullName>Customer_Tier__c</fullName>', '  <type>Picklist</type>', '  <!-- Gold | Silver | Bronze -->', '</CustomField>'],
      },
    },
  ],
  permissions: [
    { ...agentforceV1.permissions[0], after: 'read' },
    agentforceV1.permissions[1],
  ],
  tests: [
    ...agentforceV1.tests,
    {
      id: 't2',
      name: 'CaseEscalationServiceTest.raisesPriority',
      kind: 'apex',
      covers: ['ApexClass:CaseEscalationService'],
      scenario: 'happy-path',
      result: 'pass',
      coverage: 92,
      source: 'Synthetic test record',
    },
    {
      id: 't3',
      name: 'CaseEscalationServiceTest.readOnlyUserCannotEscalate',
      kind: 'apex',
      covers: ['ApexClass:CaseEscalationService'],
      scenario: 'permission',
      result: 'pass',
      coverage: 92,
      source: 'Synthetic test record',
    },
    {
      id: 't4',
      name: 'Conversation: unverified customer asks to escalate (refused)',
      kind: 'agent-conversation',
      covers: ['GenAiPlannerBundle:Case_Triage_Agent', 'GenAiPlugin:Case_Triage_Topic', 'GenAiFunction:Escalate_Case'],
      scenario: 'negative',
      result: 'pass',
      source: 'Synthetic test record',
    },
    {
      id: 't5',
      name: 'Conversation: escalate a case the agent user cannot edit (refused)',
      kind: 'agent-conversation',
      covers: ['GenAiFunction:Escalate_Case', 'GenAiFunction:Summarise_Case'],
      scenario: 'permission',
      result: 'pass',
      source: 'Synthetic test record',
    },
    {
      id: 't6',
      name: 'Prompt: summary when Customer_Tier__c is blank',
      kind: 'prompt',
      covers: ['GenAiPromptTemplate:Case_Summary'],
      scenario: 'negative',
      result: 'pass',
      source: 'Synthetic test record',
    },
  ],
};

const slaSlice: Slice = {
  id: 'case-sla-v1',
  name: 'Case SLA fields and routing',
  revision: 1,
  atomic: false,
  description: 'Human-authored changes: an SLA due date, routing that uses it, and clean-up of a legacy field.',
  provenance: 'Synthetic seed: fictional human-authored change set.',
  changes: [
    {
      id: 'b1',
      type: 'CustomField',
      apiName: 'Case.SLA_Due__c',
      action: 'add',
      origin: 'human',
      author: 'M. Laine',
      summary: 'Date/time the first response is due.',
      dependsOn: ['CustomObject:Case'],
      field: { after: { dataType: 'DateTime' }, populatedRecords: 0 },
      diff: { before: [], after: ['<CustomField>', '  <fullName>SLA_Due__c</fullName>', '  <type>DateTime</type>', '</CustomField>'] },
    },
    {
      id: 'b2',
      type: 'Flow',
      apiName: 'Case_Assignment',
      action: 'modify',
      origin: 'human',
      author: 'M. Laine',
      summary: 'Routes by Region__c and sets SLA_Due__c from priority.',
      dependsOn: ['CustomField:Case.SLA_Due__c', 'CustomField:Case.Region__c'],
      diff: {
        before: ['<decisions>', '  <name>By_Legacy_Region</name>', '  <field>Legacy_Region__c</field>', '</decisions>'],
        after: [
          '<decisions>',
          '  <name>By_Region</name>',
          '  <field>Region__c</field>',
          '</decisions>',
          '<assignments>',
          '  <assignToReference>$Record.SLA_Due__c</assignToReference>',
          '</assignments>',
        ],
      },
    },
    {
      id: 'b3',
      type: 'ApexClass',
      apiName: 'CaseRouter',
      action: 'modify',
      origin: 'human',
      author: 'J. Park',
      summary: 'Sorts the queue by SLA_Due__c.',
      dependsOn: ['CustomField:Case.SLA_Due__c'],
      diff: {
        before: ['  ORDER BY CreatedDate ASC'],
        after: ['  ORDER BY SLA_Due__c ASC NULLS LAST, CreatedDate ASC'],
      },
    },
    {
      id: 'b4',
      type: 'CustomField',
      apiName: 'Case.Legacy_Region__c',
      action: 'delete',
      origin: 'human',
      author: 'J. Park',
      summary: 'Removes the legacy region field now that routing uses Region__c.',
      dependsOn: [],
      field: { before: { dataType: 'Text', length: 80 }, populatedRecords: 3412 },
      diff: { before: ['<CustomField>', '  <fullName>Legacy_Region__c</fullName>', '  <type>Text</type>', '  <length>80</length>', '</CustomField>'], after: [] },
    },
  ],
  permissions: [],
  tests: [
    {
      id: 's1',
      name: 'CaseRouterTest.sortsBySlaDue',
      kind: 'apex',
      covers: ['ApexClass:CaseRouter'],
      scenario: 'happy-path',
      result: 'pass',
      coverage: 88,
      source: 'Synthetic test record',
    },
    {
      id: 's2',
      name: 'Flow test: Case_Assignment routes EMEA case',
      kind: 'flow',
      covers: ['Flow:Case_Assignment'],
      scenario: 'happy-path',
      result: 'pass',
      source: 'Synthetic test record',
    },
  ],
};

export function seedRelease(): Release {
  return structuredClone({
    id: 'harbourline-2026-10',
    name: 'Harbourline service release 2026.10',
    source: 'seed',
    targetOrg: { name: 'Harbourline production (synthetic inventory)', components: TARGET_COMPONENTS },
    slices: [agentforceV1, slaSlice],
  } satisfies Release);
}

export function remediationFor(sliceId: string): Slice | null {
  return sliceId === agentforceV1.id ? structuredClone(agentforceV2) : null;
}
